config/routes.rb
NewEnglish::Application.routes.draw do
  get 'quizpages/index'

  get 'quizpages/new'

  get 'examquestions/index'

  get "scramblers/index"
  get "matches/update"
  get "clozequestions/new"
  get "clozequestions/index"
  get "classnotes/index"
  get "classnotes/new"
  get "vocadrills/index"
  get "vocadrills/new"
  mount Ckeditor::Engine => '/ckeditor'
  resources :lessonvocas

  get "vocabularies/index"
  get "vocabularies/new"
  get "matchquestions/index"
  get "lessons/index"
  get "sessions/new"
  get "welcome/index"
  get "welcome/index_user"
  get "welcome/index_song"
  get "welcome/index_story"
  get "welcome/index_grammar"
  get "welcome/index_phonics"
  get "welcome/index_vocabulary"
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'

  
  root 'welcome#index'

  
	resources :todos

	 resources :classnotes
	 resources :exams do
	 	resources :examquestions do
			member do
				get 'take'
			end
			member do
				post 'processquestion'
				post 'remove_from_exam'
			end
		end
	 end
	 
  	 resources :lessons do
	    member do
		    get 'show_vocabulary'
			get 'add_vocabulary'
			post 'save_vocabulary'
			post 'remove_vocabulary'
			
			get 'add_user'
			post 'save_user'

			get 'delete_user'
			post 'remove_user'
			
		end
		resources :quizs do
			member do
				get 'add_questions'
				get 'add_questions_error'
				get 'take_quiz'
				post 'select_questions'
				post 'save_questions'
			end
			resources :quizpages do
				member do
					get 'take'
					get 'add_clozequestion'
				end
				member do
					post 'processpage'
					post 'remove_from_quiz'
				end
			end
		end
	 end

		 resources :vocabularies do
		    member do
				get 'drills'
				get 'questions'
			end
		 end
		 
			resources :multichoicequestions do
				member do
					get 'take'
				end
				member do
					post 'remove_from_quiz'
				end
			end
		 
	 resources :users do
		member do
			get 'add_lessons'
			get 'remove_lessons'
			post 'update_add_lessons'
			post 'update_remove_lessons'
			get 'assign_level'
			post 'update_level'
		end	 
	    resources :quizs do
			member do
				get 'list_questionresults'
				post 'delete_questionresults'
			end
			resources :quizquestionresults
			
		end
	 end
	   
	 resources :sessions
	 
	 resources :scramblers do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 
	 resources :fillquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :matchquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :clozequestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 

end

app/models/classnote.rb
class Classnote < ActiveRecord::Base
end

app/models/clozequestion.rb
class Clozequestion < ActiveRecord::Base
	has_many :question_clozequestions, dependent: :destroy
	accepts_nested_attributes_for :question_clozequestions, :allow_destroy => true
	has_many :quizquestions, dependent: :destroy
end

app/models/exam.rb
class Exam < ActiveRecord::Base
	   has_many :examquestions, dependent: :destroy
end

app/models/examquestion.rb
class Examquestion < ActiveRecord::Base
end

app/models/fillquestion.rb
class Fillquestion < ActiveRecord::Base
	has_many :quizquestions, dependent: :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
   has_many :lessonvocas
   has_many :vocabularies, :through => :lessonvocas
   
   has_many :userlessons
   has_many :users, :through => :userlessons
   
   has_many :quizzes, dependent: :destroy
end

app/models/lessonvoca.rb
class Lessonvoca < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :matchquestion
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
    has_many :quizpages, dependent: :destroy
	belongs_to :lesson
	#has_many :quizquestions, dependent: :destroy
end
 

app/models/quizpage.rb
class Quizpage < ActiveRecord::Base
	belongs_to :quiz
	
	has_many :question_clozequestions, dependent: :destroy
	accepts_nested_attributes_for :question_clozequestions, :allow_destroy => true

	has_many :question_matchquestions, dependent: :destroy
	accepts_nested_attributes_for :question_matchquestions, :allow_destroy => true
	
	has_many :question_multichoicequestions, dependent: :destroy
	accepts_nested_attributes_for :question_multichoicequestions, :allow_destroy => true

	#has_many :quizquestions, dependent: :destroy
	
	def next
		quiz.quizpages.where("id > ?", id).order("id ASC").first
	end
	
end

app/models/quizquestion.rb
class Quizquestion < ActiveRecord::Base
	#belongs_to :quiz
	has_one :quizquestionresult, dependent: :destroy
	#has_many :matchquestions
	belongs_to :matchquestion
	belongs_to :multichoicequestion
	belongs_to :fillquestion
	belongs_to :clozequestion
	def next
		quiz.quizquestions.where("id > ?", id).order("id ASC").first
	end
end

app/models/scrambler.rb
class Scrambler < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :uservocas
	has_many :vocabularies, :through => :uservocas
	
	has_many :userlessons
	has_many :lessons, :through => :userlessons
	
	has_many :quizquestionresults, dependent: :destroy
	
end

app/models/userlesson.rb
class Userlesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/uservoca.rb
class Uservoca < ActiveRecord::Base
  belongs_to :user
  belongs_to :vocabulary
end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
   has_many :lessonvocas
   has_many :lessons, :through => :lessonvocas
   
   has_many :uservocas
   has_many :users, :through => :uservocas
   
   has_many :multichoicequestions
end

app/models/vocadrill.rb
class Vocadrill < ActiveRecord::Base
	belongs_to :vocabulary
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/shared/_form.html.erb
 <%= form_for @multichoicequestion, url: multichoicequestions_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  
  <%= f.fields_for :question_multichoices do |q| %>
     <p class="fields">
    <%= q.label :name, "question" %><br>
    <%= q.text_area :content %>
	</p>
  <% end %>   

    <p>
    <%= f.label :choice_label_display_mode%><br>
  <%= f.select :choice_label_display_mode, options_for_select([['text','text'],['image','image'],['audio','audio']], :selected => params[:choice_label_display_mode]) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', multichoicequestions_path %>

app/views/shared/_form_clozequestion_edit.html.erb
<%= form_for @clozequestion, url: clozequestion_path, method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :instruction %><br>
    <%= f.text_area :instruction %>
  </p>
  
  <a href="javascript:addBox('question');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>

	<%= f.label :questions %><br>
	<br>
    <%= f.fields_for :question_clozequestions do |q| %>
     <p class="fields">
    <%= q.text_area :question %>
	</p>
  <% end %>   

	<p>
    <%= f.label :media%><br>
    <%= f.text_field :media %>
    </p>    

<p><%= collection_select :quiz, "id", Quiz.all, :id, :name %></p>

  <p>
  <%= check_box_tag "add_to_quiz" %>Add this question to selected quiz:
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Cloze questions index', clozequestions_path %>

app/views/shared/_form_clozequestion_new.html.erb
<%= form_for @clozequestion, url: clozequestions_path(:quiz_id => @quiz_id,:lesson_id => @lesson_id ) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :instruction %><br>
	<%= f.cktext_area :instruction, :value => '', :id => 'myinstruction' %>
  </p>
  
  <a href="javascript:addBox('question');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>

	<%= f.label :questions %><br>
	<br>
    <%= f.fields_for :question_clozequestions do |q| %>
     <p class="fields">
    <%= q.text_area :question %>
	</p>
  <% end %>   

	<p>
    <%= f.label :media%><br>
    <%= f.text_field :media %>
    </p>    

<p><%= collection_select :quiz, "id", Quiz.all, :id, :name %></p>

  <p>
  <%= check_box_tag "add_to_quiz" %>Add this question to selected quiz:
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', multichoicequestions_path %>

app/views/shared/_form_edit.html.erb
<%= form_for @multichoicequestion, url: multichoicequestion_path, method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  
  <%= f.fields_for :question_multichoices do |q| %>
     <p>
    <%= q.label :name, "question" %><br>
    <%= q.text_field :content, :rows => 3 %>
	<%= q.check_box :_destroy %>
	<%= q.label :_destroy, "Remove Question" %>
	</p>
  <% end %>
   
  <% if @vocabulary != nil %>
    <p> Voca name = <%= @vocabulary.name %></p>
    <p>
    <%= f.label :vocabulary%><br>
    <%= f.text_field :vocabulary, :value => @vocabulary.name %>
    </p>
   <% else %>
    <p>
    <%= f.label :vocabulary%><br>
    <%= f.text_field :vocabulary %>
    </p>    
   <% end %>
  <p>
    <%= f.label :media%><br>
    <%= f.text_field :media %>
    </p>    
	
	    <p>
    <%= f.label :choice_label_display_mode%><br>
  <%= f.select :choice_label_display_mode, options_for_select([['text','text'],['image','image'],['audio','audio']], :selected => params[:choice_label_display_mode]) %>
  </p>

    <p>
    <%= f.label :choice1%><br>
    <%= f.text_area :choice1 %>
  </p>  
      <p>
    <%= f.label :choice2%><br>
    <%= f.text_area :choice2 %>
  </p>  
    <p>
    <%= f.label :choice3%><br>
    <%= f.text_area :choice3 %>
  </p>  
  
  <p>
    <%= f.label :answer%><br>
    <%= f.text_field :answer %>
  </p>  

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shared/_form_multichoicequestion_edit.html.erb
<%= form_for @multichoicequestion, url: multichoicequestion_path, method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>

    <p>
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </p>

  <a href="javascript:addBox('choice');">
			<i id = "add_edit" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove_edit" class="fa fa-minus-circle fa-2x"></i>
			</a>

  <br>
  <%= f.label :choices%><br>
				
  <%= f.fields_for :choices_multichoicequestions do |q| %>
     <p class="fields">
    <%= q.text_area :choice %>
	</p>
  <% end %>   
   
  <% if @vocabulary != nil %>
    <p> Voca name = <%= @vocabulary.name %></p>
    <p>
    <%= f.label :vocabulary%><br>
    <%= f.text_field :vocabulary, :value => @vocabulary.name %>
    </p>
   <% else %>
    <p>
    <%= f.label :vocabulary%><br>
    <%= f.text_field :vocabulary %>
    </p>    
   <% end %>
  <p>
    <%= f.label :media%><br>
    <%= f.text_field :media %>
    </p>    
	
	    <p>
    <%= f.label :choice_label_display_mode%><br>
  <%= f.select :choice_label_display_mode, options_for_select([['text','text'],['image','image'],['audio','audio']], :selected => params[:choice_label_display_mode]) %>
  </p>
  <p>
    <%= f.label :answer%><br>
    <%= f.text_field :answer %>
  </p>  

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shared/_form_multichoicequestion_new.html.erb
 <%= form_for @multichoicequestion, url: multichoicequestions_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
    <p>
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </p>
  
<a href="javascript:addBox('choice');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>
  <br>
  <%= f.label :choices %><br>
  <%= f.fields_for :choices_multichoicequestions do |q| %>
     <p class="fields">
    <%= q.text_area :choice %>
	</p>
  <% end %>   
  
    <p>
    <%= f.label :choice_label_display_mode%><br>
  <%= f.select :choice_label_display_mode, options_for_select([['text','text'],['image','image'],['audio','audio']], :selected => params[:choice_label_display_mode]) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', multichoicequestions_path %>

app/views/shared/_form_quizpage_clozequestion_new.html.erb
<%= form_for (@quiz_page), url: lesson_quiz_quizpages_path(:lesson_id => @lesson_id , :quiz_id => @quiz_id) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :instruction %><br>
	<%= f.cktext_area :instruction, :value => '', :id => 'myinstruction' %>
  </p>
  
  <a href="javascript:addBox('question');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>

	<%= f.label :questions %><br>
	<br>
    <%= f.fields_for :question_clozequestions do |q| %>
     <p class="fields">
    <%= q.text_area :question %>
	</p>
  <% end %>   

<p><%= collection_select :quiz, "id", Quiz.all, :id, :name %></p>

  <p>
  <%= check_box_tag "add_to_quiz" %>Add this question to selected quiz:
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', multichoicequestions_path %>

app/views/shared/_form_quizpage_new.html.erb
<%= form_for (@quiz_page), url: lesson_quiz_quizpages_path(:lesson_id => @lesson_id , :quiz_id => @quiz_id) do |f| %>

   <%= f.hidden_field :question_type, value: question_type %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.label :instruction %><br>
	<%= f.cktext_area :instruction, :value => '', :id => 'myinstruction' %>
  </p>
  
<% if question_type == 'clozequestion' %>
  <a href="javascript:addBox('question');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>

	<%= f.label :questions %><br>
	<br>
    <%= f.fields_for :question_clozequestions do |q| %>
     <p class="fields">
    <%= q.text_area :question %>
	</p>
  <% end %>
<% elsif question_type == 'matchquestion' %>  
  <a href="javascript:addBoxes('question','answer');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>
	
	<%= f.label :questions %><br>
	<br>
    <%= f.fields_for :question_matchquestions do |q| %>
     <p class="fields">
    <%= q.text_area :question %>
	<%= q.text_area :answer %>
	</p>
  <% end %>
  <% elsif question_type == 'multichoicequestion' %>  
  <a href="javascript:add3Boxes('choice1','choice2','choice3');">
			<i id = "add" class="fa fa-plus-circle fa-2x"></i>
			</a>

<a href="javascript:removeBox();">
			<i id = "remove" class="fa fa-minus-circle fa-2x"></i>
			</a>
	
	<%= f.label :choices %><br>

	<br>
  <%= f.label :choices %><br>
  <%= f.fields_for :question_multichoicequestions do |q| %>
     <p class="fields">
    <%= q.text_area :choice1 %>
	<%= q.text_area :choice2 %>
	<%= q.text_area :choice3 %>
	</p>
  <% end %>   

	<% end %>

<p><%= collection_select :quiz, "id", Quiz.all, :id, :name %></p>

    <p>
  <%= check_box_tag "add_to_quiz" %>Add this question to this quiz:
  </p>
  <p><strong>OR</p>
  <p>
  <%= check_box_tag "add_to_selected_quiz" %> Add this question to selected quiz:
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', multichoicequestions_path %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
  	  <div id = "user_nav">
	  <% if current_user %>
	  Logged in as <%= current_user.name %>
	  <%= link_to "Log out", log_out_path %>
	  <% else %>
	  <%= link_to "Log me in", log_in_path %>
	  <% end %>
	  </div>
    <div class="navbar-header">
      <a class="navbar-brand" href="/"></a>
    </div>
  </div>
</nav>

app/views/shared/_tab_navigation.html.erb
   <% if active_tab == "Home" %>
	<li class="active"><%= link_to 'Home', welcome_index_path %></li> 
  <% else %>
	<li><%= link_to 'Home', welcome_index_path %></li>
  <% end %>
  
  <% if active_tab == "song" %>
	<li class="active"><%= link_to 'Songs', lessons_path(:display => "song") %></li> 
  <% else %>
	<li><%= link_to 'Songs', lessons_path(:display => "song") %></li>
  <% end %>

    <% if active_tab == "story" %>
	<li class="active"><%= link_to 'Stories', lessons_path(:display => "story") %></li> 
  <% else %>
	<li><%= link_to 'Stories', lessons_path(:display => "story") %></li>
  <% end %>

  <% if active_tab == "vocabulary" %>
	<li class="active"><%= link_to 'Vocabulary', lessons_path(:display => "vocabulary") %></li> 
  <% else %>
	<li><%= link_to 'Vocabulary', lessons_path(:display => "vocabulary") %></li>
  <% end %>

    <% if active_tab == "phonics" %>
	<li class="active"><%= link_to 'Phonics', lessons_path(:display => "phonics") %></li> 
  <% else %>
	<li><%= link_to 'Phonics', lessons_path(:display => "phonics") %></li>
  <% end %>

    <% if active_tab == "grammar" %>
	<li class="active"><%= link_to 'Grammar', lessons_path(:display => "grammar") %></li> 
  <% else %>
	<li><%= link_to 'Grammar', lessons_path(:display => "grammar") %></li>
  <% end %>