config/routes.rb
NewEnglish::Application.routes.draw do
  get 'quizpages/index'

  get 'quizpages/new'

  get 'examquestions/index'

  get "scramblers/index"
  get "matches/update"
  get "clozequestions/new"
  get "clozequestions/index"
  get "classnotes/index"
  get "classnotes/new"
  get "vocadrills/index"
  get "vocadrills/new"
  mount Ckeditor::Engine => '/ckeditor'
  resources :lessonvocas

  get "vocabularies/index"
  get "vocabularies/new"
  get "matchquestions/index"
  get "lessons/index"
  get "sessions/new"
  get "welcome/index"
  get "welcome/index_user"
  get "welcome/index_song"
  get "welcome/index_story"
  get "welcome/index_grammar"
  get "welcome/index_phonics"
  get "welcome/index_vocabulary"
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'

  
  root 'welcome#index'

  
	resources :todos

	 resources :classnotes
	 resources :exams do
	 	resources :examquestions do
			member do
				get 'take'
			end
			member do
				post 'processquestion'
				post 'remove_from_exam'
			end
		end
	 end
	 
  	 resources :lessons do
	    member do
		    get 'show_vocabulary'
			get 'add_vocabulary'
			post 'save_vocabulary'
			post 'remove_vocabulary'
			
			get 'add_user'
			post 'save_user'

			get 'delete_user'
			post 'remove_user'
			
		end
		resources :quizs do
			member do
				get 'add_questions'
				get 'add_questions_error'
				get 'take_quiz'
				post 'select_questions'
				post 'save_questions'
			end
			resources :quizpages do
				member do
					get 'take'
					get 'add_clozequestion'
				end
				member do
					post 'processpage'
					post 'remove_from_quiz'
				end
			end
		end
	 end

		 resources :vocabularies do
		    member do
				get 'drills'
				get 'questions'
			end
		 end
		 
			resources :multichoicequestions do
				member do
					get 'take'
				end
				member do
					post 'remove_from_quiz'
				end
			end
		 
	 resources :users do
		member do
			get 'add_lessons'
			get 'remove_lessons'
			post 'update_add_lessons'
			post 'update_remove_lessons'
			get 'assign_level'
			post 'update_level'
		end	 
	    resources :quizs do
			member do
				get 'list_questionresults'
				post 'delete_questionresults'
			end
			resources :quizquestionresults
			
		end
	 end
	   
	 resources :sessions
	 
	 resources :scramblers do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 
	 resources :fillquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :matchquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :clozequestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 

end

app/models/classnote.rb
class Classnote < ActiveRecord::Base
end

app/models/clozequestion.rb
class Clozequestion < ActiveRecord::Base
	has_many :question_clozequestions, dependent: :destroy
	accepts_nested_attributes_for :question_clozequestions, :allow_destroy => true
	has_many :quizquestions, dependent: :destroy
end

app/models/exam.rb
class Exam < ActiveRecord::Base
	   has_many :examquestions, dependent: :destroy
end

app/models/examquestion.rb
class Examquestion < ActiveRecord::Base
end

app/models/fillquestion.rb
class Fillquestion < ActiveRecord::Base
	has_many :quizquestions, dependent: :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
   has_many :lessonvocas
   has_many :vocabularies, :through => :lessonvocas
   
   has_many :userlessons
   has_many :users, :through => :userlessons
   
   has_many :quizzes, dependent: :destroy
end

app/models/lessonvoca.rb
class Lessonvoca < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :matchquestion
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
    has_many :quizpages, dependent: :destroy
	belongs_to :lesson
	#has_many :quizquestions, dependent: :destroy
end
 

app/models/quizpage.rb
class Quizpage < ActiveRecord::Base
	belongs_to :quiz
	
	has_many :question_clozequestions, dependent: :destroy
	accepts_nested_attributes_for :question_clozequestions, :allow_destroy => true

	has_many :question_matchquestions, dependent: :destroy
	accepts_nested_attributes_for :question_matchquestions, :allow_destroy => true
	
	has_many :question_multichoicequestions, dependent: :destroy
	accepts_nested_attributes_for :question_multichoicequestions, :allow_destroy => true

	#has_many :quizquestions, dependent: :destroy
	
	def next
		quiz.quizpages.where("id > ?", id).order("id ASC").first
	end
	
end

app/models/quizquestion.rb
class Quizquestion < ActiveRecord::Base
	#belongs_to :quiz
	has_one :quizquestionresult, dependent: :destroy
	#has_many :matchquestions
	belongs_to :matchquestion
	belongs_to :multichoicequestion
	belongs_to :fillquestion
	belongs_to :clozequestion
	def next
		quiz.quizquestions.where("id > ?", id).order("id ASC").first
	end
end

app/models/scrambler.rb
class Scrambler < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :uservocas
	has_many :vocabularies, :through => :uservocas
	
	has_many :userlessons
	has_many :lessons, :through => :userlessons
	
	has_many :quizquestionresults, dependent: :destroy
	
end

app/models/userlesson.rb
class Userlesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/uservoca.rb
class Uservoca < ActiveRecord::Base
  belongs_to :user
  belongs_to :vocabulary
end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
   has_many :lessonvocas
   has_many :lessons, :through => :lessonvocas
   
   has_many :uservocas
   has_many :users, :through => :uservocas
   
   has_many :multichoicequestions
end

app/models/vocadrill.rb
class Vocadrill < ActiveRecord::Base
	belongs_to :vocabulary
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
     #@todos = Todo.all
     if current_user
	    #@my_lesson = current_user.lesson
	    #@my_lesson = Lesson.find(current_user.lesson_id)

	    #render text: @my_lesson.name
	 end
  end

  def index_song
     if current_user
	    @active_tab = 'Songs'
	    #@my_lesson = Lesson.find(current_user.lesson_id)
	    #render text: @my_lesson.name
	 end
  end
  
  def index_user
     if current_user
	    #@my_lessons = current_user.lessons
	    #@my_lesson = Lesson.find(current_user.lesson_id)
	    #render text: @my_lesson.name
	 end
  end

  
  def index_story
     if current_user
		@stories = Array.new
		current_user.lessons.each do |lesson|
			if lesson.content_type == 'story'
				@stories.push(lesson)
			end 
		end
	 end
  end

  
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if current_user %>
  <ul class="nav nav-tabs" role="tablist">
  <li  class="active"><%= link_to 'Home', welcome_index_path %></li>
  <li><%= link_to 'Songs', lessons_path(:display => "song") %></li>
  <li><%= link_to 'Stories', lessons_path(:display => "story") %></li>
  <li><%= link_to 'Vocabulary', lessons_path(:display => "vocabulary") %></li>
  <li><%= link_to 'Phonics', lessons_path(:display => "phonics") %></li>
  <li><%= link_to 'Grammar', lessons_path(:display => "grammar") %></li>
  </ul>
  <br>
  <h2>Welcome <%= current_user.real_name %> to TATH.com</h2>
  <h2><strong>Your level: <%= current_user.level %></strong>&nbsp<i class="fa fa-star"></i></h2>
<br>
<% if current_user.name == "kpham" %>
<%= link_to 'New Lesson', new_lesson_path , class: 'btn btn-success' %>
<% end %>
<% end %>
<br>
<br>

app/views/welcome/index_song.html.erb
		      <ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Home', welcome_index_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
  <li  class="active"><%= link_to 'Songs', welcome_index_song_path %></li>
  <li><%= link_to 'Stories', welcome_index_story_path %></li>
  
  </ul>

			<p><strong>Your level: <%= current_user.level %></strong>&nbsp<i class="fa fa-star"></i></p>
			<p><strong>Your Songs:</strong></p>
			        <ul>
					<% current_user.lessons.each do |lesson| %>
					<% if lesson.content_type == 'song' %>
					<li><%= link_to lesson.name, lesson_path(lesson.id) %></li>
					<% end %>
					<% end %>
				    </ul>

app/views/welcome/index_story.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Home', welcome_index_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
  <li><%= link_to 'Songs', welcome_index_song_path %></li>
  <li class="active"><%= link_to 'Stories', welcome_index_story_path %></li>
  </ul>
  
  <h1>Your stories</h1>
			<p><strong>Your Stories: ( <%= @stories.count %>) </strong></p>
			        <ul>
					<% current_user.lessons.each do |lesson| %>
					<% if lesson.content_type == 'story' %>
					<li><%= link_to lesson.name, lesson_path(lesson.id) %></li>
					<% end %>
					<% end %>
				    </ul>

app/views/welcome/index_user.html.erb
		      <ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Home', welcome_index_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
  <li><%= link_to 'Songs', welcome_index_user_path %></li>
  </ul>

			<p><strong>Your level: <%= current_user.level %></strong>&nbsp<i class="fa fa-star"></i></p>
			<p><strong>Your Lessons:</strong></p>
			        <ul>
					<% current_user.lessons.each do |lesson| %>
					<li><%= link_to lesson.name, lesson_path(lesson.id) %></li>
					<% end %>
				    </ul>