config/routes.rb
NewEnglish::Application.routes.draw do
  get 'quizpages/index'

  get 'quizpages/new'

  get 'examquestions/index'

  get "scramblers/index"
  get "matches/update"
  get "clozequestions/new"
  get "clozequestions/index"
  get "classnotes/index"
  get "classnotes/new"
  get "vocadrills/index"
  get "vocadrills/new"
  mount Ckeditor::Engine => '/ckeditor'
  resources :lessonvocas

  get "vocabularies/index"
  get "vocabularies/new"
  get "matchquestions/index"
  get "lessons/index"
  get "sessions/new"
  get "welcome/index"
  get "welcome/index_user"
  get "welcome/index_song"
  get "welcome/index_story"
  get "welcome/index_grammar"
  get "welcome/index_phonics"
  get "welcome/index_vocabulary"
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'

  
  root 'welcome#index'

  
	resources :todos

	 resources :classnotes
	 resources :exams do
	 	resources :examquestions do
			member do
				get 'take'
			end
			member do
				post 'processquestion'
				post 'remove_from_exam'
			end
		end
	 end
	 
  	 resources :lessons do
	    member do
		    get 'show_vocabulary'
			get 'add_vocabulary'
			post 'save_vocabulary'
			post 'remove_vocabulary'
			
			get 'add_user'
			post 'save_user'

			get 'delete_user'
			post 'remove_user'
			
		end
		resources :quizs do
			member do
				get 'add_questions'
				get 'add_questions_error'
				get 'take_quiz'
				post 'select_questions'
				post 'save_questions'
			end
			resources :quizpages do
				member do
					get 'take'
					get 'add_clozequestion'
				end
				member do
					post 'processpage'
					post 'remove_from_quiz'
				end
			end
		end
	 end

		 resources :vocabularies do
		    member do
				get 'drills'
				get 'questions'
			end
		 end
		 
			resources :multichoicequestions do
				member do
					get 'take'
				end
				member do
					post 'remove_from_quiz'
				end
			end
		 
	 resources :users do
		member do
			get 'add_lessons'
			get 'remove_lessons'
			post 'update_add_lessons'
			post 'update_remove_lessons'
			get 'assign_level'
			post 'update_level'
		end	 
	    resources :quizs do
			member do
				get 'list_questionresults'
				post 'delete_questionresults'
			end
			resources :quizquestionresults
			
		end
	 end
	   
	 resources :sessions
	 
	 resources :scramblers do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 
	 resources :fillquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :matchquestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 resources :clozequestions do
		member do
			get 'take'
		end
		member do
			post 'remove_from_quiz'
		end
	 end

	 

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
   has_many :lessonvocas
   has_many :vocabularies, :through => :lessonvocas
   
   has_many :userlessons
   has_many :users, :through => :userlessons
   
   has_many :quizzes, dependent: :destroy
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
     @lessons = Lesson.all
	 @display = params[:display]
	 @active_tab = @display
  end
  
  def new
  end

  def edit
	@lesson = Lesson.find(params[:id])
	@matches = Match.where("matchquestion_id = ?",5)
  end

  def add_user
     #render text: params.inspect
	 @lesson = Lesson.find(params[:id])
	 @all_users = User.order(:name)
  end
  
  def save_user
	  #render text: params.inspect
	  @lesson = Lesson.find(params[:id])
	  mykeys = params.keys  
	  #params format:   user_ID => 1 (selected)
	  #examples         user_1 => 1
	  #         		user_9 => 1
		 
	  mykeys.each do |k|
	   if (k.include? "user")
	    arr = k.split('_')		
		user_id = arr[1].to_i
		    @user = User.find(user_id)
			@lesson.users << @user
		end
	  end
	  redirect_to lessons_path
  end

  def delete_user
     #render text: params.inspect
	 @lesson = Lesson.find(params[:id])
  end

  def remove_user
     #render text: params.inspect
	 @lesson = Lesson.find(params[:id])
	 mykeys = params.keys  
	  #params format:   user_ID => 1 (selected)
	  #examples         user_1 => 1
	  #         		user_9 => 1
		 
	  mykeys.each do |k|
	   if (k.include? "user")
	    arr = k.split('_')		
		user_id = arr[1].to_i
		    @user = User.find(user_id)
			if @lesson.users.include?(@user)
			   @lesson.users.delete(@user)
			end
		end
	  end
	  redirect_to lessons_path
  end
  
  def add_vocabulary
	@lesson = Lesson.find(params[:id])
  end

  def save_vocabulary
	@lesson = Lesson.find(params[:id])
	#render text: params[:name]
	entry = Vocabulary.find_by name: params[:name]
	#render text: entry.definition
	if entry != nil
	  @lesson.vocabularies << entry
	  redirect_to @lesson
	else
	  redirect_to new_vocabulary_path
	end
  end
  
  def show_vocabulary
	@lesson = Lesson.find(params[:id])
  end
  
  def remove_vocabulary
     #render text: params.inspect 
	 lesson = Lesson.find(params[:id])
	 voca = lesson.vocabularies.find(params[:voca_id])
	 #render text: voca.name
	 lesson.vocabularies.delete(voca)
	 #voca.destroy
	 redirect_to show_vocabulary_lesson_path(params[:id])
  end
  
  def update
     @lesson = Lesson.find(params[:id])
	 if @lesson.update(lesson_params)
	  	#redirect_to @lesson
		render 'edit'
	 else
	    render 'edit'
	 end
  end
  
  def create
  	  @lesson = Lesson.create(lesson_params)
	  #render text: params[:lesson][:level].inspect 
	  #render text: params.inspect
	  if params["add_students"] == "1"
	      lesson_level = params[:lesson][:level]
		  users_at_this_level = User.where("level = ?",lesson_level)
		  users_at_this_level.each do |user|	   	    
			@lesson.users << user		
		  end	
	  end
	  redirect_to @lesson
  end

  def add_quiz
      @lesson = Lesson.find(params[:id])
	  #render text: lesson.name
	  redirect_to new_quiz_path
  end
  
  def take_quizzes
      @lesson = Lesson.find(params[:id])
	  #@quiz = Quiz.find(@lesson.quiz_id)
	  @quizzes = @lesson.quizzes
      #redirect_to take_quizzes_lesson_path(@lesson)	  
	  #render text: @lesson.quizzes.count
  end

  def show
      @lesson = Lesson.find(params[:id])	  
	  my_quizzes = @lesson.quizzes
	  #@voca_quiz = Quiz.find_by quiz_type: 'vocabulary'
	  my_quizzes.each do |quiz|
	     if quiz.quiz_type == "vocabulary"
		    @voca_quiz = quiz
			break
		 end
	  end

	  my_quizzes.each do |quiz|
	     if quiz.quiz_type == "grammar"
		    @grammar_quiz = quiz
			break
		 end
	  end

	  my_quizzes.each do |quiz|
	     if quiz.quiz_type == "phonics"
		    @phonics_quiz = quiz
			break
		 end
	  end

	  my_quizzes.each do |quiz|
	     if quiz.quiz_type == "general"
		    @general_quiz = quiz
			break
		 end
	  end
	  
	  #@grammar_quiz = Quiz.find_by quiz_type: 'grammar'
	  #@phonics_quiz = Quiz.find_by quiz_type: 'phonics'
	  #@general_quiz = Quiz.find_by quiz_type: 'general'
	  #@quiz = Quiz.find(@lesson.quiz_id)
	  #@quiz = @lesson.quiz
	  #@take_quiz_link = "location.href=" + "'" + take_quiz_lesson_path + "'"
	  #@take_quizzes_link = "location.href=" + "'" + lesson_quizs_path + "'"
	  @take_quizzes_link = "location.href=" + "'" + lesson_quizs_path(@lesson) + "'"
	  #redirect_to lesson_quizs_path(@lesson)
  end
  
  def destroy
	  #render text: params[:id].inspect
      @lesson = Lesson.find(params[:id])
	  users_for_this_lesson = @lesson.users
	  users_for_this_lesson.each do |user|
		 user.lessons.delete(@lesson)
	  end
	  @lesson.destroy
	  redirect_to lessons_path
  end

  private
  def lesson_params
	params.require(:lesson).permit(:name, :reading_content, :vocabulary_content, :grammar_content, :phonics_content, :lyrics_content, :video, :level, :content_type)
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/add_user.html.erb
<h3> Add users for lesson: <%= @lesson.name %> Level: <strong><%= @lesson.level %></strong></h3>
<%= form_tag save_user_lesson_path :method=>'post' do %>
    <% @all_users.each do |user| %>
	    <% if @lesson.users.include?(user) == false %>
		<%= check_box_tag 'user_'+user.id.to_s %> <%= user.name %> ( <strong><%= user.level %>)</strong>
		<% end %>
	<p>
	<% end %>
	</p>
	<p>
	<%= submit_tag "Save users" %>
	</p>
<% end %>

app/views/lessons/add_vocabulary.html.erb
<h3> Add vocabulary for this lesson: </h3>
<%= form_tag save_vocabulary_lesson_path :method=>'post' do %>
	   <%= text_field_tag :name %>
	   <%= @lesson.name %>
	     <p>
        <%= submit_tag "Submit"%>
  </p>
<% end %>

app/views/lessons/delete_user.html.erb
<h3> Delete users for lesson: <%= @lesson.name %> Level: <%= @lesson.level %> </h3>
<%= form_tag remove_user_lesson_path :method=>'post' do %>
    <% @lesson.users.each do |user| %>	
		<%= check_box_tag 'user_'+user.id.to_s %> <%= user.name %> level = <%= user.level %>
	<p>
	<% end %>
	</p>
	<p>
	<%= submit_tag "Delecte selected users" %>
	</p>
<% end %>

app/views/lessons/edit.html.erb
<h2> EDIT LESSON </h2>
<%= form_for :lesson, url: lesson_path(@lesson), method: :patch do |f| %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :content_type %><br>
    <%= f.select :content_type, options_for_select([['song','song'],['story','story'],['vocabulary','vocabulary'],['phonics','phonics'],['grammar','grammar']], :selected => @lesson.content_type) %>
</p>

  <p>
    <%= f.label :reading %><br>
    <%= f.cktext_area :reading_content, :id => 'mycontent' %>
  </p>

    <p>
    <%= f.label :vocabulary %><br>
    <%= f.cktext_area :vocabulary_content, :id => 'myvocabulary_content' %>
  </p>

    <p>
    <%= f.label :grammar %><br>
    <%= f.cktext_area :grammar_content, :id => 'mygrammar' %>
  </p>
  
    <p>
    <%= f.label :phonics %><br>
    <%= f.cktext_area :phonics_content, :id => 'myphonics' %>
  </p>

   <p>
    <%= f.label :lyrics %><br>
    <%= f.cktext_area :lyrics_content, :id => 'mylyrics' %>
  </p>

  <p>
    <%= f.label :video%><br>
    <%= f.text_field :video %>
  </p>  
  
    <p>
  <%= f.label :level%><br>
  <%= f.select :level, options_for_select([['Basic','Basic'],['Intermediate','Intermediate'],['Advanced','Advanced'],['Expert','Expert']], :selected => @lesson.level) %>
  </p> 
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Home', welcome_index_path %>

app/views/lessons/index.html.erb
<ul class="nav nav-tabs" role="tablist">
<%= render partial: 'shared/tab_navigation', locals: {active_tab: @active_tab} %>
</ul>
  <br>  
<% if current_user.name == 'kpham' %>
<h1>Lessons (<%= @active_tab %>) listing</h1>
<h4><strong><%= link_to 'New Lesson', new_lesson_path %></strong></h4>
<% @lessons.each do |lesson| %>
<% if lesson.content_type == @display %>
	<p>
	<h4>Lesson <%= lesson.id %>&nbsp<%= lesson.name %></h4>
	<table class = 'table' >
	<tr>
	<td><strong><%= link_to 'Show',lesson_path(lesson) %></strong></td>
	<td>&nbsp</td>
    <td><strong><%= link_to 'Edit', edit_lesson_path(lesson) %></strong></td>
	<td><strong><%= button_to "Delete ", { action: "destroy", id: lesson.id }, method: :delete, data: { confirm: "Are you sure?" } %></strong></td>
	</tr>
	</table>
	There are <%= lesson.quizzes.count %> quizzes for this lesson
	<%= link_to 'Show', lesson_quizs_path(lesson) %>
	 <%= link_to 'Add a quiz', new_lesson_quiz_path(lesson) %>
	</p>
	<p>
	    There are <%= lesson.users.count %> users for this lesson (the lessons for these users will be deleted upon lesson's deletion) :
	</p>
		<% lesson.users.each do |user| %>
			 <%= user.name %>
		<% end %>
	<p>
	 <strong><%= link_to 'Delete user', delete_user_lesson_path(lesson) %></strong>
	<strong><%= link_to 'Add user', add_user_lesson_path(lesson) %></strong>
	
  <% end %>
  <% end %>
  <% else %>
	<h2>Your lessons (<%= @active_tab %>) listing</h2>
	<table class = "table" >
	<% current_user.lessons.each do |lesson| %>
	<% if lesson.content_type == @display %>
	    <tr>
		<td>
		<p><%= lesson.name %><p>
		</td>
		<td><%= link_to 'Learn', lesson_path(lesson.id)%></td>
		</tr>
	<% end %>
	<% end %>
	</table>
  <% end %>
  </p>
  

app/views/lessons/new.html.erb
<%= form_for :lesson, url: lessons_path do |f| %>
<p>
Create a new lesson
</p>
<p>
Create a new lesson
</p>
<p>
Create a new lesson
</p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :reading %><br>
    <%= f.cktext_area :reading_content, :value => '', :id => 'mycontent' %>
  </p>

    <p>
    <%= f.label :vocabulary %><br>
    <%= f.cktext_area :vocabulary_content, :value => '', :id => 'myvocabulary_content' %>
  </p>

    <p>
    <%= f.label :grammar %><br>
    <%= f.cktext_area :grammar_content, :value => '', :id => 'mygrammar' %>
  </p>
  
    <p>
    <%= f.label :phonics %><br>
    <%= f.cktext_area :phonics_content, :value => '', :id => 'myphonics' %>
  </p>

   <p>
    <%= f.label :lyrics %><br>
    <%= f.cktext_area :lyrics_content, :value => '', :id => 'mylyrics' %>
  </p>

  <p>
    <%= f.label :video%><br>
    <%= f.text_field :video, :value => '' %>
  </p>  
  
    <p>
    <%= f.label :level%><br>
  <%= f.select :level, options_for_select([['Basic','Basic'],['Intermediate','Intermediate'],['Advanced','Advanced'],['Expert','Expert']], :selected => params[:level]) %>
  </p>
 <p>
  <%= check_box_tag "add_students" %> Add lesson lesson to students at this level
  </p>
  
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Lessons List', lessons_path %>

app/views/lessons/show.html.erb
<h2><%= @lesson.name %></h2>
<p>Level:<%= @lesson.level %></p>

<table>
<tr>
<td>
<% if !@lesson.video.blank? %>
<%= video_tag @lesson.video, :size => "320x240", :controls => true,:onended => "video_ended()" %>
<% end %>
</td>
</tr>
</table>

<% if !@lesson.lyrics_content.blank? %>
<p>
  <strong>Lyrics:</strong>
  <%= raw@lesson.lyrics_content %>
</p>
<% end %>

<% if !@lesson.reading_content.blank? %>
<p>
  <strong>Reading:</strong>
  <%= raw@lesson.reading_content %>
</p>
<% end %>

<% if !@lesson.vocabulary_content.blank? %>
<p>
  <strong>Vocabulary:</strong>
  <%= raw@lesson.vocabulary_content %>
</p>
<% end %>

 <% if @voca_quiz != nil %>
<p><i class="fa fa-question-circle fa-lg">&nbsp</i>
<%= link_to 'Vocabulary quiz', take_quiz_lesson_quiz_path(@lesson,@voca_quiz) %></p>
 <% end %>
  
<% if !@lesson.grammar_content.blank? %>
<p>
  <strong>Grammar:</strong>
  <%= raw@lesson.grammar_content %>
</p>
<% end %>

<% if @grammar_quiz != nil %>
<p><i class="fa fa-question-circle fa-lg">&nbsp</i>
<%= link_to 'Grammar quiz', take_quiz_lesson_quiz_path(@lesson,@grammar_quiz) %></p>
<% end %>

<% if !@lesson.phonics_content.blank? %>
<p>
  <strong>Phonics:</strong>
  <%= raw@lesson.phonics_content %>
</p>
<% end %>
<% if @phonics_quiz != nil %>
<p><i class="fa fa-question-circle fa-lg">&nbsp</i>
<%= link_to 'Phonics quiz', take_quiz_lesson_quiz_path(@lesson,@phonics_quiz) %></p>
<% end %>


<% if @general_quiz != nil %>
<p><i class="fa fa-question-circle fa-lg">&nbsp</i>
<%= link_to 'General quiz', take_quiz_lesson_quiz_path(@lesson,@general_quiz) %></p>
<% end %>

 <% if current_user.name == "kpham" %>
    Vocabularies: <%= link_to 'Show vocabularies', show_vocabulary_lesson_path %>
	
	Quizs:
	<p>There are <%= @lesson.quizzes.count %> quizzes for this lesson</p>
	<table>
	<% @lesson.quizzes.each do |quiz| %>
    <tr>
	  <td><%= link_to quiz.name, lesson_quiz_path(@lesson,quiz.id) %></td>
	  <td><%=  link_to 'Take', take_quiz_lesson_quiz_path(@lesson,quiz) %></td>
	</tr>
	<% end %>
    </table>
	
 <p><%= link_to 'Edit Lesson', edit_lesson_path(@lesson) %></p>
 <p><%= link_to 'Add a quiz', new_lesson_quiz_path(@lesson) %></p>
 <p><%= link_to 'Back to lesson index', lessons_path %></p>
 <% else %>
<% end %>

app/views/lessons/show_vocabulary.erb
<h1>Lesson: <%= @lesson.name %></h1>
<p>Level:<%= @lesson.level %></p>
<p>Vocabularies for this lesson: </p>
	<table>
	<% @lesson.vocabularies.each do |voca| %>
    <tr>
	  <td><strong><%= voca.name %></strong></td>
	  <% @definition_hash = eval(voca.definition) %>	  
	  <% @definition_hash.each do |key, value| %>
	      <td><%= key %></td>
		  <td>:</td>
		  <td><%= value %></td>
	  <% end %>
	  <td><%= link_to "Vocabulary drills", edit_vocabulary_path(voca.id) %></td>
	  <% if current_user.name == "kpham" %>
	  <td><%= link_to "Edit", edit_vocabulary_path(voca.id) %></td>
	  <td>
	  	  <%= button_to "Delete ", { controller: "lessons", action: "remove_vocabulary", id: @lesson.id, voca_id: voca.id}, method: :post, data: { confirm: "Are you sure?" } %>
	  </td>
	  <% end %>
    </tr>
	<% end %>
	</table>
	<% if current_user.name == "kpham" %>
	<%= link_to "Add vocabulary", add_vocabulary_lesson_path(@lesson.id) %>
	<% end %>
    <%= link_to 'Back to lesson', lesson_path(@lesson) %>
	<%= link_to 'Home', welcome_index_path %>
	<%= link_to 'Vocabulary exercises', welcome_index_path %>